#' @title Establish a New blaseRtemplates Installation
#' @description This function sets up a directory structure that is designed to work well with blaseRtemplates functions.  It will create directories where indicated, write a standard .Rprofile document, and modify the user .Renviron file to configure R properly.  The function will not overwrite existing directories and will fail when an existing installation is already present in the same location.  The only modification outside of the existing directory is to the .Renviron file.  If you have existing configurations in your .Renviron file, they will only be changed if they are conflicting.  If this is problematic, then you should archive your .Renviron file before running.  The new .Renviron file will cause R to use the new .Rprofile in the cache directory and skip existing user- and project-level .Rprofiles.
#'
#' For the individual user:  Identify the location for your blaseRtemplates cache and your R projects.  For convenience, these can be within the same parent directory.  The cache will hold versioned and hashed binary package files in the library directory.  These are the actual instructions used by R when you call up functions.  The version/hash structure is tracked by your projects and allows reproducibility.  The user_project directory holds symlinks to the specific version/hash packages being used.  A new directory is created for each new project.  The source directory is used by the package installer, pak, to archive the source files for each package.  You should rarely need to look in there.  The logs directory holds .Rhistory files.  One is created for each R session you open.  The .tsv files catalog the entire collection of packages in your cache with their dependencies.  The .Rprofile is what sets up your R session to use the proper user_package directory, ensures you are working in a valid project, generates startup messages and sets some helpful options.
#'
#' This function will create 1 project, called baseproject, in the projects directory which will ensure you are always operating in a project environment.  Working outside of a project can have dangerous/unintended consequences.
#'
#' For the system administrator:  the directory structure will work equally well for a multiuser system (e.g. rstudio server) with minor modifications.  The .Rprofile generated by the function can be used as Rprofile.site and will apply to all users of that R installation.  Each user should have their own project directories with a baseproject on the system.  The .Renviron file should be modified for each user to point to this directory and saved in the home directory.  There should be a subdirectory in user_projects with each user's ID for their project libraries.  Ownership should be given to the user/group and permissions set accordingly, e.g. 755.
#'
#' Upgrading R versions:  since package binaries don't work across minor version changes in R, e.g. 4.2 -> 4.3, you will have to create a new cache directory each time this changes.
#'
#' @param cache_path Path to the blaseRtemplates cache root. Should include the R major and minor version numbers in the final directory.  This and all intermediate directories will be created.
#' @param project_path Path to the R projects directory.  For convenience, can put this in the same parent directory as cache_path, but not strictly necessary.
#' @examples
#' \dontrun{
#' if(interactive()){
#'   establish_new_bt(cache_path = "<some_directory>/r_4_2_cache", project_path = "<some_directory>/projects")
#'  }
#' }
#' @seealso
#'  \code{\link[cli]{cli_alert}}
#'  \code{\link[fs]{create}}, \code{\link[fs]{copy}}, \code{\link[fs]{path_package}}, \code{\link[fs]{path}}, \code{\link[fs]{file_access}}, \code{\link[fs]{dir_ls}}, \code{\link[fs]{path_file}}
#'  \code{\link[stringr]{str_detect}}, \code{\link[stringr]{str_replace}}
#'  \code{\link[usethis]{proj_utils}}
#' @rdname establish_new_bt
#' @export
#' @importFrom cli cli_alert_warning cli_alert_info
#' @importFrom fs dir_create file_copy path_package path file_exists dir_walk dir_copy path_file
#' @importFrom stringr str_detect str_replace
#' @importFrom usethis with_project
establish_new_bt <- function(cache_path, project_path) {
  cli::cli_alert_warning(
    "This function will establish a new installation of R compatible with current blaseRtemplates functions.\nIt will:  "
  )
  cat("1. Create a new directory in the supplied path holding the cache.\n")
  cat("2. Create a new directory in the supplied path holding for R projects.\n")
  cat("3. Modify/add the user-level .Renviron file in your home directory.\n")
  cat("4. Create a new baseproject in the projects directory.\n\n")
  cli::cli_alert_warning("You should not proceed unless you are aware of what this means.")
  answer <-  menu(c("Yes", "No"), title = "Do you wish to proceed?")
  if (answer == 1) {
    # make the directory tree we will need
    fs::dir_create(cache_path, "library")
    fs::dir_create(cache_path, "user_project", Sys.getenv("USER"))
    fs::dir_create(cache_path, "source")
    fs::dir_create(cache_path, "logs")
    fs::dir_create(project_path)

    # write in some templates
    fs::file_copy(
      path = fs::path_package("templates", "R_profile.R", package = "blaseRtemplates"),
      new_path = fs::path(cache_path, ".Rprofile")
    )

    # modify the bt r environ and append to home r environ
    if (fs::file_exists(fs::path(Sys.getenv("HOME"), ".Renviron"))) {
      home_renviron <-
        readLines(fs::path(Sys.getenv("HOME"), ".Renviron"))
    } else {
      home_renviron <- character(0)
    }

    if (any(stringr::str_detect(home_renviron, "BLASERTEMPLATES"))) {
      cli::cli_alert_info(
        "\nA .Renviron file in your home directory has already been modified for blaseRtemplates installation.\nThis function will overwrite those specific configurations and leave others unmodified.\n"
      )
      home_renviron <-
        home_renviron[stringr::str_detect(
          home_renviron,
          "BLASERTEMPLATES|GITHUB_PAT|R_PKG_CACHE|R_PROFILE_USER|PATH",
          negate = TRUE
        )]

    }

    bt_renviron_path <- ifelse(
      Sys.info()[["sysname"]] == "Windows",
      fs::path_package(package = "blaseRtemplates",
                       "templates",
                       "Renviron_home_win"),
      fs::path_package(package = "blaseRtemplates",
                       "templates",
                       "Renviron_home")
    )

    bt_renviron <-
      readLines(bt_renviron_path) |>
      stringr::str_replace("R_PKG_CACHE_DIR=<>",
                           paste0("R_PKG_CACHE_DIR=",
                                  fs::path(cache_path, "source"))) |>
      stringr::str_replace(
        "BLASERTEMPLATES_CACHE_ROOT=<>",
        paste0("BLASERTEMPLATES_CACHE_ROOT=",
               fs::path(cache_path))
      ) |>
      stringr::str_replace(
        "BLASERTEMPLATES_PROJECTS=<>",
        paste0("BLASERTEMPLATES_PROJECTS=",
               fs::path(project_path))
      ) |>
      stringr::str_replace("R_PROFILE_USER=<>",
                           paste0("R_PROFILE_USER=",
                                  fs::path(cache_path,
                                           ".Rprofile")))
    writeLines(c(home_renviron, bt_renviron),
               con = fs::path(Sys.getenv("HOME"), ".Renviron"))

    # make a base project
    initialize_project(
      path = fs::path(project_path, "baseproject"),
      open = FALSE,
      fresh_install = TRUE,
      path_to_cache_root = cache_path
    )

    # populate the cache from the base library
    base_libraries <-
      .libPaths()[!grepl(x = .libPaths(), pattern = "user_project")]

    npackages <- nrow(fs::dir_info(base_libraries))

    cli::cli_alert_info("Attempting to copy {npackages} packages from the base libraries.")

    fs::dir_walk(c(base_libraries), fun = \(x) {
      if (stringr::str_detect(x, "_cache", negate = TRUE)) {
        package <- fs::path_file(x)
        tryCatch(expr = {
            fs::dir_copy(path = x,
          new_path = fs::path(
            cache_path,
            "user_project",
            Sys.info()[["user"]],
            "baseproject",
            package
          )
        )
        }, error = function(cond){
          cli::cli_alert_danger("Unable to copy {.emph {package}.  Skipping.")
        }, finally = cli::cli_alert_info("Copied {.emph {package}.")
        )

      }
    })

    Sys.setenv(BLASERTEMPLATES_CACHE_ROOT = cache_path)

    hash_n_cache(
      lib_loc = fs::path(cache_path,
                         "user_project",
                         Sys.info()[["user"]],
                         "baseproject"),
      cache_loc = fs::path(cache_path, "library")
    )


    # create the package catalog
    `%notin%` <- Negate(`%in%`)

    lib_path <- fs::path(cache_path, "library")
    package_paths <- fs::dir_ls(lib_path,
                                recurse = 2)[fs::dir_ls(lib_path,
                                                        recurse = 2) %notin% fs::dir_ls(lib_path,
                                                                                        recurse = 1)]

    fs::dir_info(package_paths, recurse = FALSE) |>
      dplyr::select(path, birth_time) |>
      dplyr::mutate(hash = fs::path_file(fs::path_dir(path))) |>
      dplyr::mutate(version = as.package_version(fs::path_file(fs::path_dir(
        fs::path_dir(path)
      )))) |>
      dplyr::mutate(name = fs::path_file(fs::path_dir(fs::path_dir(
        fs::path_dir(path)
      )))) |>
      dplyr::mutate(R_version = paste0(R.version$major, ".", R.version$minor)) |>
      dplyr::select(
        R_version,
        name,
        version,
        date_time = birth_time,
        hash,
        binary_location = path
      ) |>
      readr::write_tsv(file = fs::path(cache_path, "package_catalog.tsv"))

    # create the dependency catalog
    purrr::map_dfr(.x = fs::path_dir(
      fs::dir_ls(
        path = fs::path(cache_path, "library"),
        recurse = 4,
        regexp = "DESCRIPTION"
      )
    ),
    .f = \(x) {
      dependencies <- get_all_deps(x)
      name <- fs::path_file(x)
      hashes <- fs::path_file(fs::path_dir(x))
      tibble::tibble(name = name,
                     hashes = hashes,
                     dependencies = dependencies)
    }) |> readr::write_tsv(file = fs::path(cache_path, "dependency_catalog.tsv"))


    cli::cli_alert_success("A new blaseRtemplates installation has been created at {cache_path}.")
    cli::cli_alert_success("A new R baseproject has been created within {project_path}.")
    cli::cli_alert_info("You should now switch to the baseproject.")
    cli::cli_alert_info("See https://blaserlab.github.io/blaseRtemplates/articles/establish.html for more information.")
  }
}


#' @title Regenerate .Rprofile and .Renviron Files
#' @description If you have deleted or otherwise broken your .Rprofile or .Renviron files, you may have difficulty connecting to the package cache.  This function will regenerate both for you.  The existing .Rprofile must be deleted manually.  You can choose to archive the old version if you wish.  It will be replaced with the standard .Rprofile from blaseRtemplates.  The .Renviron file will be modified by removing the damaged lines and replacing them with the correct ones.  You must supply the correct file path locations to your cache directory and project directory, otherwise your R installation will be configured incorrectly.
#' @param cache_path path to the cache directory
#' @param project_path path to the projects directory
#' @return nothing
#' @seealso
#'  \code{\link[fs]{file_access}}, \code{\link[fs]{path}}, \code{\link[fs]{copy}}, \code{\link[fs]{path_package}}
#'  \code{\link[cli]{cli_abort}}, \code{\link[cli]{cli_alert}}
#'  \code{\link[stringr]{str_detect}}, \code{\link[stringr]{str_replace}}
#' @rdname regenerate_bt_configs
#' @export
#' @importFrom fs file_exists path file_copy path_package
#' @importFrom cli cli_abort cli_alert_info
#' @importFrom stringr str_detect str_replace
regenerate_bt_configs <- function(cache_path, project_path) {
  if (fs::file_exists(fs::path(cache_path, ".Rprofile"))) {
    cli::cli_abort(
      "Delete the existing .Rprofile at {fs::path(cache_path, '.Rprofile')} and try again."
    )
  }

  fs::file_copy(
    path = fs::path_package("templates", "R_profile.R", package = "blaseRtemplates"),
    new_path = fs::path(cache_path, ".Rprofile")
  )

  # modify the bt r environ and append to home r environ
  if (fs::file_exists(fs::path(Sys.getenv("HOME"), ".Renviron"))) {
    home_renviron <-
      readLines(fs::path(Sys.getenv("HOME"), ".Renviron"))
  } else {
    home_renviron <- character(0)
  }

  if (any(stringr::str_detect(home_renviron, "BLASERTEMPLATES"))) {
    cli::cli_alert_info(
      "\nA .Renviron file in your home directory has already been modified for blaseRtemplates installation.\nThis function will overwrite those specific configurations and leave others unmodified.\n"
    )
    home_renviron <-
      home_renviron[stringr::str_detect(
        home_renviron,
        "BLASERTEMPLATES|GITHUB_PAT|R_PKG_CACHE|R_PROFILE_USER|PATH",
        negate = TRUE
      )]

  }
  bt_renviron_path <- ifelse(
    Sys.info()[["sysname"]] == "Windows",
    fs::path_package(package = "blaseRtemplates",
                     "templates",
                     "Renviron_home_win"),
    fs::path_package(package = "blaseRtemplates",
                     "templates",
                     "Renviron_home")
  )

  bt_renviron <-
    readLines(bt_renviron_path) |>
    stringr::str_replace("R_PKG_CACHE_DIR=<>",
                         paste0("R_PKG_CACHE_DIR=",
                                fs::path(cache_path, "source"))) |>
    stringr::str_replace(
      "BLASERTEMPLATES_CACHE_ROOT=<>",
      paste0("BLASERTEMPLATES_CACHE_ROOT=",
             fs::path(cache_path))
    ) |>
    stringr::str_replace("BLASERTEMPLATES_PROJECTS=<>",
                         paste0("BLASERTEMPLATES_PROJECTS=",
                                fs::path(project_path))) |>
    stringr::str_replace("R_PROFILE_USER=<>",
                         paste0("R_PROFILE_USER=",
                                fs::path(cache_path,
                                         ".Rprofile")))


  writeLines(c(home_renviron, bt_renviron),
             con = fs::path(Sys.getenv("HOME"), ".Renviron"))


}
